services:
  postgres:
    image: postgres
    container_name: simplereading-db
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
  # app:
  #   build: .
  #   image: dockerfile
  #   container_name: simplereading-app
  #   ports:
  #     - '5090:8080'
  #   depends_on:
  #     - postgres
  #   volumes:
  #     - ./.env:/App/.env 

  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - ./nginx/sites-available:/etc/nginx/conf.d
  #   depends_on:
  #     - app


volumes:
  postgres_data:
