services:
  postgres:
    image: postgres
    container_name: simplereading-db
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=simplereading
    
  app:
    build: .
    env_file:
      - .env
    container_name: simplereading-app
    depends_on:
      - postgres
    ports:
      - '8081:8080' 


